-- ✅ 06/10/2026 — Security Advisor do Supabase (aplicado direto no banco).
-- 51 funções SECURITY DEFINER do public deixaram de ser executáveis pelo ANÔNIMO
-- (só portal_resolve_token continua, usada pelo link do portal). authenticated e
-- service_role foram garantidos explicitamente ANTES de tirar o PUBLIC (nenhum
-- perdeu acesso). Funções só de cron/gatilho também saíram do authenticated
-- (gatilho dispara sem EXECUTE — testado). Backup das ACLs antigas no scratchpad
-- da sessão (backup_acl_funcoes_2026-10-06.json).

grant execute on function appativa_admin_dispatch_check() to authenticated;
grant execute on function appativa_admin_dispatch_check() to service_role;
revoke execute on function appativa_admin_dispatch_check() from public, anon;
grant execute on function appativa_payment_dispatch_check() to authenticated;
grant execute on function appativa_payment_dispatch_check() to service_role;
revoke execute on function appativa_payment_dispatch_check() from public, anon;
grant execute on function approve_manual_payment(uuid,uuid) to authenticated;
grant execute on function approve_manual_payment(uuid,uuid) to service_role;
revoke execute on function approve_manual_payment(uuid,uuid) from public, anon;
grant execute on function billing_control_automation(uuid,uuid,text) to authenticated;
grant execute on function billing_control_automation(uuid,uuid,text) to service_role;
revoke execute on function billing_control_automation(uuid,uuid,text) from public, anon;
grant execute on function billing_enqueue_all_tenants(date) to authenticated;
grant execute on function billing_enqueue_all_tenants(date) to service_role;
revoke execute on function billing_enqueue_all_tenants(date) from public, anon;
grant execute on function billing_enqueue_scheduled(uuid,date) to authenticated;
grant execute on function billing_enqueue_scheduled(uuid,date) to service_role;
revoke execute on function billing_enqueue_scheduled(uuid,date) from public, anon;
grant execute on function can_delete_plan_table(uuid,boolean) to authenticated;
grant execute on function can_delete_plan_table(uuid,boolean) to service_role;
revoke execute on function can_delete_plan_table(uuid,boolean) from public, anon;
grant execute on function check_and_notify_low_credits(uuid,uuid) to authenticated;
grant execute on function check_and_notify_low_credits(uuid,uuid) to service_role;
revoke execute on function check_and_notify_low_credits(uuid,uuid) from public, anon;
grant execute on function clear_deep_archived(uuid,uuid) to authenticated;
grant execute on function clear_deep_archived(uuid,uuid) to service_role;
revoke execute on function clear_deep_archived(uuid,uuid) from public, anon;
grant execute on function client_message_cancel(uuid,uuid) to authenticated;
grant execute on function client_message_cancel(uuid,uuid) to service_role;
revoke execute on function client_message_cancel(uuid,uuid) from public, anon;
grant execute on function client_message_schedule(uuid,uuid,text,timestamp with time zone,text) to authenticated;
grant execute on function client_message_schedule(uuid,uuid,text,timestamp with time zone,text) to service_role;
revoke execute on function client_message_schedule(uuid,uuid,text,timestamp with time zone,text) from public, anon;
grant execute on function client_message_send_now(uuid,uuid,text,text) to authenticated;
grant execute on function client_message_send_now(uuid,uuid,text,text) to service_role;
revoke execute on function client_message_send_now(uuid,uuid,text,text) from public, anon;
grant execute on function create_client_and_setup(uuid,uuid,text,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,text,text,boolean,timestamp with time zone,boolean,text,uuid[],boolean,boolean,text,uuid,text,text,text,text,text,text,text) to authenticated;
grant execute on function create_client_and_setup(uuid,uuid,text,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,text,text,boolean,timestamp with time zone,boolean,text,uuid[],boolean,boolean,text,uuid,text,text,text,text,text,text,text) to service_role;
revoke execute on function create_client_and_setup(uuid,uuid,text,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,text,text,boolean,timestamp with time zone,boolean,text,uuid[],boolean,boolean,text,uuid,text,text,text,text,text,text,text) from public, anon;
grant execute on function create_client_and_setup(uuid,uuid,text,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,text,text,boolean,timestamp with time zone,boolean,text,uuid[],boolean,boolean,text,uuid) to authenticated;
grant execute on function create_client_and_setup(uuid,uuid,text,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,text,text,boolean,timestamp with time zone,boolean,text,uuid[],boolean,boolean,text,uuid) to service_role;
revoke execute on function create_client_and_setup(uuid,uuid,text,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,text,text,boolean,timestamp with time zone,boolean,text,uuid[],boolean,boolean,text,uuid) from public, anon;
grant execute on function create_plan_table_clone(uuid,text,currency_code,boolean,boolean) to authenticated;
grant execute on function create_plan_table_clone(uuid,text,currency_code,boolean,boolean) to service_role;
revoke execute on function create_plan_table_clone(uuid,text,currency_code,boolean,boolean) from public, anon;
grant execute on function create_reseller_and_setup(uuid,text,text,text,text,boolean,text,timestamp with time zone) to authenticated;
grant execute on function create_reseller_and_setup(uuid,text,text,text,text,boolean,text,timestamp with time zone) to service_role;
revoke execute on function create_reseller_and_setup(uuid,text,text,text,text,boolean,text,timestamp with time zone) from public, anon;
grant execute on function delete_archived_server(uuid,uuid) to authenticated;
grant execute on function delete_archived_server(uuid,uuid) to service_role;
revoke execute on function delete_archived_server(uuid,uuid) from public, anon;
grant execute on function delete_client_forever(uuid,uuid) to authenticated;
grant execute on function delete_client_forever(uuid,uuid) to service_role;
revoke execute on function delete_client_forever(uuid,uuid) from public, anon;
grant execute on function delete_reseller_forever(uuid,uuid) to authenticated;
grant execute on function delete_reseller_forever(uuid,uuid) to service_role;
revoke execute on function delete_reseller_forever(uuid,uuid) from public, anon;
grant execute on function delete_server_hard(uuid,uuid,uuid) to authenticated;
grant execute on function delete_server_hard(uuid,uuid,uuid) to service_role;
revoke execute on function delete_server_hard(uuid,uuid,uuid) from public, anon;
grant execute on function ensure_default_plan_tables(uuid) to authenticated;
grant execute on function ensure_default_plan_tables(uuid) to service_role;
revoke execute on function ensure_default_plan_tables(uuid) from public, anon;
grant execute on function get_last_reseller_sale(uuid,uuid) to authenticated;
grant execute on function get_last_reseller_sale(uuid,uuid) to service_role;
revoke execute on function get_last_reseller_sale(uuid,uuid) from public, anon;
grant execute on function get_my_visible_apps() to authenticated;
grant execute on function get_my_visible_apps() to service_role;
revoke execute on function get_my_visible_apps() from public, anon;
grant execute on function get_server_integration_token(uuid) to authenticated;
grant execute on function get_server_integration_token(uuid) to service_role;
revoke execute on function get_server_integration_token(uuid) from public, anon;
grant execute on function handle_new_user() to authenticated;
grant execute on function handle_new_user() to service_role;
revoke execute on function handle_new_user() from public, anon;
grant execute on function import_set_client_extras(uuid,uuid,text,text,timestamp with time zone) to authenticated;
grant execute on function import_set_client_extras(uuid,uuid,text,text,timestamp with time zone) to service_role;
revoke execute on function import_set_client_extras(uuid,uuid,text,text,timestamp with time zone) from public, anon;
grant execute on function link_reseller_to_server(uuid,uuid,uuid,text,text,numeric) to authenticated;
grant execute on function link_reseller_to_server(uuid,uuid,uuid,text,text,numeric) to service_role;
revoke execute on function link_reseller_to_server(uuid,uuid,uuid,text,text,numeric) from public, anon;
grant execute on function log_client_archive_restore_event() to authenticated;
grant execute on function log_client_archive_restore_event() to service_role;
revoke execute on function log_client_archive_restore_event() from public, anon;
grant execute on function log_manual_renewal_payment(uuid,uuid,numeric,text,text,text,timestamp with time zone,text) to authenticated;
grant execute on function log_manual_renewal_payment(uuid,uuid,numeric,text,text,text,timestamp with time zone,text) to service_role;
revoke execute on function log_manual_renewal_payment(uuid,uuid,numeric,text,text,text,timestamp with time zone,text) from public, anon;
grant execute on function log_server_credit_purchase_only(uuid,uuid,numeric,numeric,currency_code,numeric,numeric,text) to authenticated;
grant execute on function log_server_credit_purchase_only(uuid,uuid,numeric,numeric,currency_code,numeric,numeric,text) to service_role;
revoke execute on function log_server_credit_purchase_only(uuid,uuid,numeric,numeric,currency_code,numeric,numeric,text) from public, anon;
grant execute on function log_trial_conversion_event() to authenticated;
grant execute on function log_trial_conversion_event() to service_role;
revoke execute on function log_trial_conversion_event() from public, anon;
grant execute on function log_trial_created_event() to authenticated;
grant execute on function log_trial_created_event() to service_role;
revoke execute on function log_trial_created_event() from public, anon;
grant execute on function manual_deep_archive_client(uuid,uuid) to authenticated;
grant execute on function manual_deep_archive_client(uuid,uuid) to service_role;
revoke execute on function manual_deep_archive_client(uuid,uuid) from public, anon;
grant execute on function renew_client_and_log(uuid,uuid,integer,text,text,timestamp with time zone,text,numeric,numeric,boolean) to authenticated;
grant execute on function renew_client_and_log(uuid,uuid,integer,text,text,timestamp with time zone,text,numeric,numeric,boolean) to service_role;
revoke execute on function renew_client_and_log(uuid,uuid,integer,text,text,timestamp with time zone,text,numeric,numeric,boolean) from public, anon;
grant execute on function requeue_message_jobs(uuid,uuid[]) to authenticated;
grant execute on function requeue_message_jobs(uuid,uuid[]) to service_role;
revoke execute on function requeue_message_jobs(uuid,uuid[]) from public, anon;
grant execute on function resolve_notification(uuid,text,text) to authenticated;
grant execute on function resolve_notification(uuid,text,text) to service_role;
revoke execute on function resolve_notification(uuid,text,text) from public, anon;
grant execute on function sell_credits_to_reseller_and_log(uuid,uuid,uuid,numeric,numeric,currency_code,numeric,text) to authenticated;
grant execute on function sell_credits_to_reseller_and_log(uuid,uuid,uuid,numeric,numeric,currency_code,numeric,text) to service_role;
revoke execute on function sell_credits_to_reseller_and_log(uuid,uuid,uuid,numeric,numeric,currency_code,numeric,text) from public, anon;
grant execute on function sell_credits_to_reseller_without_balance(uuid,uuid,uuid,numeric,numeric,currency_code,numeric,text) to authenticated;
grant execute on function sell_credits_to_reseller_without_balance(uuid,uuid,uuid,numeric,numeric,currency_code,numeric,text) to service_role;
revoke execute on function sell_credits_to_reseller_without_balance(uuid,uuid,uuid,numeric,numeric,currency_code,numeric,text) from public, anon;
grant execute on function set_client_apps(uuid,uuid,uuid[]) to authenticated;
grant execute on function set_client_apps(uuid,uuid,uuid[]) to service_role;
revoke execute on function set_client_apps(uuid,uuid,uuid[]) from public, anon;
grant execute on function set_reseller_phones(uuid,uuid,text,text[]) to authenticated;
grant execute on function set_reseller_phones(uuid,uuid,text,text[]) to service_role;
revoke execute on function set_reseller_phones(uuid,uuid,text,text[]) from public, anon;
grant execute on function set_tenant_fx_rates(uuid,numeric,numeric,date,text) to authenticated;
grant execute on function set_tenant_fx_rates(uuid,numeric,numeric,date,text) to service_role;
revoke execute on function set_tenant_fx_rates(uuid,numeric,numeric,date,text) from public, anon;
grant execute on function toggle_server_archive(uuid) to authenticated;
grant execute on function toggle_server_archive(uuid) to service_role;
revoke execute on function toggle_server_archive(uuid) from public, anon;
grant execute on function topup_server_credits_and_log(uuid,uuid,numeric,numeric,currency_code,numeric,numeric,text) to authenticated;
grant execute on function topup_server_credits_and_log(uuid,uuid,numeric,numeric,currency_code,numeric,numeric,text) to service_role;
revoke execute on function topup_server_credits_and_log(uuid,uuid,numeric,numeric,currency_code,numeric,numeric,text) from public, anon;
grant execute on function trg_tenant_members_sync_tenant() to authenticated;
grant execute on function trg_tenant_members_sync_tenant() to service_role;
revoke execute on function trg_tenant_members_sync_tenant() from public, anon;
grant execute on function unlink_reseller_from_server(uuid,uuid) to authenticated;
grant execute on function unlink_reseller_from_server(uuid,uuid) to service_role;
revoke execute on function unlink_reseller_from_server(uuid,uuid) from public, anon;
grant execute on function update_client(uuid,uuid,text,text,text,boolean,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,boolean,boolean,text,timestamp with time zone,boolean,text,boolean,uuid,text,text,text,text,text,text,text,boolean) to authenticated;
grant execute on function update_client(uuid,uuid,text,text,text,boolean,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,boolean,boolean,text,timestamp with time zone,boolean,text,boolean,uuid,text,text,text,text,text,text,text,boolean) to service_role;
revoke execute on function update_client(uuid,uuid,text,text,text,boolean,uuid,text,text,integer,text,numeric,currency_code,timestamp with time zone,boolean,boolean,text,timestamp with time zone,boolean,text,boolean,uuid,text,text,text,text,text,text,text,boolean) from public, anon;
grant execute on function update_fulfillment_status(uuid,uuid,text) to authenticated;
grant execute on function update_fulfillment_status(uuid,uuid,text) to service_role;
revoke execute on function update_fulfillment_status(uuid,uuid,text) from public, anon;
grant execute on function update_reseller(uuid,uuid,text,text,text,boolean,boolean,text,timestamp with time zone,boolean) to authenticated;
grant execute on function update_reseller(uuid,uuid,text,text,text,boolean,boolean,text,timestamp with time zone,boolean) to service_role;
revoke execute on function update_reseller(uuid,uuid,text,text,text,boolean,boolean,text,timestamp with time zone,boolean) from public, anon;
grant execute on function update_server_credits_manual(uuid,numeric,text) to authenticated;
grant execute on function update_server_credits_manual(uuid,numeric,text) to service_role;
revoke execute on function update_server_credits_manual(uuid,numeric,text) from public, anon;
grant execute on function update_server_credits_manual(uuid,numeric) to authenticated;
grant execute on function update_server_credits_manual(uuid,numeric) to service_role;
revoke execute on function update_server_credits_manual(uuid,numeric) from public, anon;
grant execute on function update_whatsapp_status(uuid,uuid,text) to authenticated;
grant execute on function update_whatsapp_status(uuid,uuid,text) to service_role;
revoke execute on function update_whatsapp_status(uuid,uuid,text) from public, anon;
-- cron/gatilho: tira do authenticated
grant execute on function appativa_admin_dispatch_check() to service_role;
revoke execute on function appativa_admin_dispatch_check() from authenticated;
grant execute on function appativa_payment_dispatch_check() to service_role;
revoke execute on function appativa_payment_dispatch_check() from authenticated;
grant execute on function billing_enqueue_all_tenants(date) to service_role;
revoke execute on function billing_enqueue_all_tenants(date) from authenticated;
grant execute on function ensure_default_plan_tables(uuid) to service_role;
revoke execute on function ensure_default_plan_tables(uuid) from authenticated;
grant execute on function log_client_archive_restore_event() to service_role;
revoke execute on function log_client_archive_restore_event() from authenticated;
grant execute on function log_trial_conversion_event() to service_role;
revoke execute on function log_trial_conversion_event() from authenticated;
grant execute on function log_trial_created_event() to service_role;
revoke execute on function log_trial_created_event() from authenticated;
grant execute on function trg_tenant_members_sync_tenant() to service_role;
revoke execute on function trg_tenant_members_sync_tenant() from authenticated;
